# Generated by Django 3.1.1 on 2021-09-23 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rms', '0020_bhdb'),
    ]

    operations = [
        migrations.AddField(
            model_name='bhdb',
            name='Count',
            field=models.IntegerField(blank=True, help_text='Total Under Warranty Systems', null=True),
        ),
    ]
