# Generated by Django 3.1.1 on 2021-09-23 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rms', '0021_bhdb_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='dbdata',
            name='Date',
            field=models.DateField(blank=True, help_text='Date of Last Updte', null=True),
        ),
    ]
