# Generated by Django 3.1.1 on 2021-09-24 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rms', '0022_dbdata_date'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SiteData',
        ),
        migrations.DeleteModel(
            name='SiteDetails',
        ),
        migrations.AddField(
            model_name='bhsitedetails',
            name='Is_Active',
            field=models.BooleanField(default=True, help_text='Active Status'),
        ),
    ]
